language: python
python:
    - "2.7"

sudo: false

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - export PYTHONPATH=$PYTHONPATH:$PWD
  - # flake8 .
  - py.test -vs tests/
