name: devito
channels:
  - defaults
  - conda-forge
dependencies:
  - python >=3.6
  - numpy >=1.11
  - sympy >=1.1
  - scipy
  - matplotlib
  - pytest
  - flake8>=2.1.0
  - nbval
  - cached-property
  - psutil>=5.1.0
  - sphinx
  - sphinx_rtd_theme
  - dask
  - distributed
  - pip:
    - "git+git://github.com/inducer/cgen"
    - "git+git://github.com/inducer/codepy"
    - py-cpuinfo
